version: '3'
services:
  bitza:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/app
#      - /storages/bitza/documents:/app/documents

    depends_on:
      - db
      - migrations

  db:
    image: postgres:latest
    ports:
      - "5434:5434"
    command:
      - "postgres"
      - "-c"
      - "port=5434"
    env_file:
      - .env

  migrations:
    build:
      context: .
    command: [ "python", "manage.py", "migrate", "--no-input" ]
    restart: "no"
    depends_on:
      - db
    volumes:
      - ./:/app