version: '3'
services:
  bitza:
    container_name: bitza-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    volumes:
      - /var/www/documents:/app/documents
    depends_on:
      - db
    networks:
      - shared-net

  db:
    image: postgres:latest
    container_name: bitza-db
    ports:
      - "5434:5434"
    command:
      - "postgres"
      - "-c"
      - "port=5434"
    env_file:
      - .env
    networks:
      - shared-net

networks:
  shared-net:
    external: true