services:
  db:
    image: postgres:latest
    container_name: bitza-db
    ports:
      - "5434:5434"
    command:
      - "postgres"
      - "-c"
      - "port=5434"
    env_file:
      - .env
    volumes:
      - ${HOME}/databases/bitza:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bitza-net

networks:
  bitza-net:
    external: true