# Generated by Django 4.1 on 2023-06-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_payment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date_begin', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('payed', models.IntegerField()),
                ('diff', models.IntegerField()),
                ('month_diff', models.DecimalField(decimal_places=1, max_digits=10)),
                ('paid_months', models.DecimalField(decimal_places=1, max_digits=10)),
                ('debt_month', models.DecimalField(decimal_places=1, max_digits=10)),
                ('debt_rur', models.IntegerField()),
            ],
            options={
                'db_table': 'expected_payments',
                'managed': False,
            },
        ),
    ]
