   name: Deploy

   on:
     push:
       branches:
         - main

   jobs:
     deploy:
       runs-on: ubuntu-latest

       steps:
         - name: Send deploy request
           run: |
             curl -X POST ${{ secrets.DEPLOY_URL }} \
             -H "deploy-token: ${{ secrets.DEPLOY_TOKEN }}"
